import { CheckCircle2, LockKeyhole } from "lucide-react";

export default function AuthLayout({ children }: { children: React.ReactNode }) {
  return <div className="flex min-h-dvh flex-col bg-canvas">
    <header className="flex min-h-14 items-center justify-between border-b bg-card px-5 sm:px-8"><div className="flex items-center gap-3"><span className="grid size-8 place-items-center rounded-lg bg-primary text-sm font-semibold text-primary-foreground">P</span><span className="font-semibold">Parallax</span><span className="hidden border-l pl-3 text-xs text-muted-foreground sm:inline">Local operations workspace</span></div><span className="flex items-center gap-2 text-xs text-muted-foreground"><span className="size-1.5 rounded-full bg-success" />Secure session</span></header>
    <main className="mx-auto grid w-full max-w-6xl flex-1 items-center gap-12 px-5 py-10 sm:px-8 lg:grid-cols-[minmax(0,1.05fr)_minmax(420px,.95fr)] lg:gap-24">
      <aside className="hidden lg:block"><p className="text-xs font-medium text-primary">CONTROLLED ENGINEERING AUTOMATION</p><h2 className="mt-4 max-w-md text-4xl font-semibold leading-[1.15] tracking-[-0.035em]">Engineering work,<br />with context and control.</h2><p className="mt-5 max-w-md text-sm leading-6 text-muted-foreground">Bring your connected tools into one workspace. Review proposed changes and follow each mission through verification.</p><ol className="mt-10 space-y-6">{[["01", "Collect context", "Connect evidence from GitHub, Jira, and Notion."], ["02", "Review the proposal", "Approve changes before the agent writes to your tools."], ["03", "Verify the outcome", "Follow execution results and the recorded timeline."]].map(([number, title, copy]) => <li key={number} className="flex gap-4"><span className="grid size-8 shrink-0 place-items-center rounded-full border bg-card font-mono text-xs text-primary">{number}</span><div><h3 className="text-sm font-semibold">{title}</h3><p className="mt-1 text-sm text-muted-foreground">{copy}</p></div></li>)}</ol><div className="mt-10 grid grid-cols-2 gap-3"><div className="rounded-xl border bg-card p-4"><LockKeyhole className="size-4 text-primary" /><p className="mt-3 text-sm font-medium">Locally hosted</p><p className="mt-1 text-xs text-muted-foreground">No cloud dependency.</p></div><div className="rounded-xl border bg-card p-4"><CheckCircle2 className="size-4 text-success" /><p className="mt-3 text-sm font-medium">Approval gated</p><p className="mt-1 text-xs text-muted-foreground">Writes stay controlled.</p></div></div></aside>
      <div className="flex justify-center">{children}</div>
    </main>
    <footer className="flex min-h-12 items-center justify-between border-t bg-card px-5 text-xs text-muted-foreground sm:px-8"><span>Parallax · Local-first workflow system</span><span className="font-mono">API session protected</span></footer>
  </div>;
}
