import { Suspense } from "react";
import Link from "next/link";
import { Activity, Filter, Link2 } from "lucide-react";
import { PanelSkeleton } from "@/components/page-skeleton";
import { PageHeader } from "@/components/page-header";
import { Button } from "@/components/ui/button";
import { getAuditEvents } from "@/lib/api/server";

const pageSize = 50;

async function ActivityPageContent({ searchParams }: { searchParams: Promise<{ page?: string; mission_id?: string; event_type?: string; event?: string }> }) {
  const query = await searchParams;
  const page = Math.max(1, Number.parseInt(query.page ?? "1", 10) || 1);
  const events = await getAuditEvents({ mission_id: query.mission_id || undefined, event_type: query.event_type || undefined, limit: pageSize, offset: pageSize * (page - 1) });
  const selected = events.find((event) => event.id === query.event) ?? events[0];
  const paramsFor = (changes: Record<string, string | undefined>) => { const params = new URLSearchParams(); if (query.mission_id) params.set("mission_id", query.mission_id); if (query.event_type) params.set("event_type", query.event_type); params.set("page", String(page)); for (const [key, value] of Object.entries(changes)) { if (value) params.set(key, value); else params.delete(key); } return `/activity?${params}`; };
  return <main className="mx-auto max-w-[1440px] px-4 pb-8 sm:px-6 lg:px-8">
    <form className="mb-5 grid gap-3 rounded-xl border bg-card p-4 shadow-xs sm:grid-cols-[1fr_1fr_auto]"><label className="sr-only" htmlFor="mission-filter">Mission UUID</label><input id="mission-filter" name="mission_id" defaultValue={query.mission_id} placeholder="Mission UUID" className="min-h-10 rounded-lg border bg-background px-3 text-sm outline-none focus:border-primary focus:ring-2 focus:ring-primary/15" /><label className="sr-only" htmlFor="event-filter">Event type</label><input id="event-filter" name="event_type" defaultValue={query.event_type} placeholder="Event type" className="min-h-10 rounded-lg border bg-background px-3 text-sm outline-none focus:border-primary focus:ring-2 focus:ring-primary/15" /><Button type="submit"><Filter />Apply filters</Button></form>
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1.45fr)_minmax(320px,.55fr)]">
      <section className="overflow-hidden rounded-xl border bg-card"><div className="flex items-center justify-between border-b bg-surface-inset px-5 py-4"><div><h2 className="font-semibold">Audit timeline</h2><p className="mt-1 text-xs text-muted-foreground">{events.length} events on this page</p></div><Activity className="size-4 text-primary" /></div><ol className="divide-y">{events.map((event) => <li key={event.id}><Link href={paramsFor({ event: event.id })} className={`grid grid-cols-[18px_minmax(0,1fr)_auto] gap-3 px-5 py-4 hover:bg-surface-inset ${selected?.id === event.id ? "bg-primary-subtle" : ""}`}><span className="mt-1.5 size-2 rounded-full bg-primary" /><div className="min-w-0"><h3 className="truncate text-sm font-medium">{event.event_type.replaceAll("_", " ")}</h3><p className="mt-1 truncate font-mono text-xs text-muted-foreground">{event.mission_id ?? "Workspace event"}</p></div><time className="text-xs text-muted-foreground" dateTime={event.created_at}>{new Date(event.created_at).toLocaleString()}</time></Link></li>)}{!events.length && <li className="py-12 text-center text-sm text-muted-foreground">No audit events match these filters.</li>}</ol></section>
      <aside className="rounded-xl border bg-card p-5"><p className="text-[11px] font-semibold uppercase tracking-[0.08em] text-muted-foreground">Event inspector</p>{selected ? <><h2 className="mt-5 font-semibold capitalize">{selected.event_type.replaceAll("_", " ")}</h2><time className="mt-1 block text-xs text-muted-foreground" dateTime={selected.created_at}>{new Date(selected.created_at).toLocaleString()}</time><dl className="mt-5 space-y-4 text-sm"><div><dt className="text-xs text-muted-foreground">Mission</dt><dd className="mt-1 break-all font-mono text-xs">{selected.mission_id ?? "Workspace event"}</dd></div><div><dt className="text-xs text-muted-foreground">Actor</dt><dd className="mt-1 break-all font-mono text-xs">{selected.actor_user_id ?? "System"}</dd></div><div><dt className="flex items-center gap-1 text-xs text-muted-foreground"><Link2 className="size-3" />Correlation ID</dt><dd className="mt-1 break-all font-mono text-xs">{selected.correlation_id}</dd></div></dl>{Object.keys(selected.payload).length > 0 ? <pre className="mt-5 max-h-72 overflow-auto rounded-lg border bg-surface-inset p-3 text-xs">{JSON.stringify(selected.payload, null, 2)}</pre> : <p className="mt-5 rounded-lg border bg-surface-inset p-3 text-xs text-muted-foreground">This event has no additional payload.</p>}</> : <p className="mt-5 text-sm text-muted-foreground">Select an event to inspect it.</p>}</aside>
    </div>
    <div className="mt-5 flex justify-between"><Button nativeButton={false} variant="outline" disabled={page === 1} render={page > 1 ? <Link href={paramsFor({ page: String(page - 1), event: undefined })} /> : undefined}>Previous</Button><span className="self-center font-mono text-xs">Page {page}</span><Button nativeButton={false} variant="outline" disabled={events.length < pageSize} render={events.length === pageSize ? <Link href={paramsFor({ page: String(page + 1), event: undefined })} /> : undefined}>Next</Button></div>
  </main>;
}

export default function ActivityPage(props: { searchParams: Promise<{ page?: string; mission_id?: string; event_type?: string; event?: string }> }) {
  return <><div className="mx-auto max-w-[1440px] px-4 pt-6 sm:px-6 lg:px-8"><PageHeader eyebrow="Immutable history" title="Audit activity" description="Trace every mission event and inspect backend correlation data." /></div><Suspense fallback={<div className="mx-auto max-w-[1440px] px-4 pb-8 sm:px-6 lg:px-8"><PanelSkeleton rows={8} /></div>}><ActivityPageContent {...props} /></Suspense></>;
}
