import { CheckCircle2, CircleHelp, Database, Server, Settings2, Users, Workflow } from "lucide-react";
import { PageHeader } from "@/components/page-header";
import { StreamResource } from "@/components/stream-resource";
import { getApiHealth, getCurrentWorkspace, getHealth, getReady, requireSession } from "@/lib/api/server";

const sections = [{ label: "System status", icon: Server }, { label: "Workspace", icon: Settings2 }, { label: "Members", icon: Users }, { label: "Workflows", icon: Workflow }];
const statusStyle = (value: string) => value === "up" || value === "ok" || value === "ready" ? "bg-success-soft text-success" : value === "down" || value === "not_ready" ? "bg-danger-soft text-destructive" : "bg-muted text-muted-foreground";

export default function SettingsPage() {
  return <main className="mx-auto max-w-[1440px] px-4 py-6 sm:px-6 lg:px-8">
    <PageHeader eyebrow="System and session" title="Settings" description="Workspace identity, available workspaces, and backend readiness." />
    <div className="grid items-start gap-5 lg:grid-cols-[220px_minmax(0,1fr)]">
      <nav className="rounded-xl border bg-card p-2" aria-label="Settings sections">{sections.map(({ label, icon: Icon }, index) => <div key={label} className={`flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm ${index === 0 ? "bg-primary-subtle font-medium text-primary" : "text-muted-foreground"}`}><Icon className="size-4" />{label}</div>)}</nav>
      <div className="space-y-5">
        <StreamResource promise={Promise.all([getHealth(), getApiHealth(), getReady()])} label="System status">{([health, apiHealth, ready]) => { const services = [{ name: "Application API", value: health.status, detail: health.service, icon: Server }, { name: "Compatibility API", value: apiHealth.status, detail: apiHealth.service, icon: CircleHelp }, { name: "Postgres", value: ready?.dependencies.postgres ?? "unknown", detail: "Durable mission storage", icon: Database }, { name: "Redis", value: ready?.dependencies.redis ?? "unknown", detail: "Queue coordination", icon: Database }, { name: "Worker", value: ready?.dependencies.worker ?? "unknown", detail: "Mission execution", icon: Workflow }]; return <section className="overflow-hidden rounded-xl border bg-card"><header className="flex items-start justify-between border-b bg-surface-inset px-5 py-4"><div><h2 className="font-semibold">System status</h2><p className="mt-1 text-xs text-muted-foreground">Live readiness from the local Parallax backend.</p></div><span className={`rounded-md px-2 py-1 text-xs ${statusStyle(ready?.status ?? "unknown")}`}>{ready?.status?.replaceAll("_", " ") ?? "unknown"}</span></header><div className="grid gap-px bg-border sm:grid-cols-2 xl:grid-cols-3">{services.map(({ name, value, detail, icon: Icon }) => <div key={name} className="bg-card p-5"><div className="flex items-center justify-between"><span className="grid size-9 place-items-center rounded-lg border bg-surface-inset"><Icon className="size-4" /></span><span className={`rounded-md px-2 py-1 text-xs capitalize ${statusStyle(value)}`}>{value.replaceAll("_", " ")}</span></div><h3 className="mt-4 text-sm font-semibold">{name}</h3><p className="mt-1 text-xs text-muted-foreground">{detail}</p></div>)}</div><footer className="flex flex-wrap items-center justify-between gap-3 border-t px-5 py-3 text-xs text-muted-foreground"><span className="flex items-center gap-2"><CheckCircle2 className="size-3.5 text-success" />Direct server checks · no browser cache</span><span className="font-mono">Uptime {Math.round(health.uptime_seconds)}s</span></footer></section>; }}</StreamResource>
        <StreamResource promise={Promise.all([getCurrentWorkspace(), requireSession()])} label="Workspace">{([workspace, session]) => <section className="rounded-xl border bg-card p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-semibold">Workspace identity</h2><p className="mt-1 text-xs text-muted-foreground">Session-safe details returned by the backend.</p></div><span className="rounded-md bg-primary-subtle px-2 py-1 text-xs capitalize text-primary">{workspace.role}</span></div><dl className="mt-5 grid gap-3 sm:grid-cols-2"><div className="rounded-lg border bg-surface-inset p-3"><dt className="text-xs text-muted-foreground">Name</dt><dd className="mt-1 text-sm font-medium">{workspace.name}</dd></div><div className="rounded-lg border bg-surface-inset p-3"><dt className="text-xs text-muted-foreground">Slug</dt><dd className="mt-1 font-mono text-xs">{workspace.slug}</dd></div><div className="rounded-lg border bg-surface-inset p-3 sm:col-span-2"><dt className="text-xs text-muted-foreground">Workspace ID</dt><dd className="mt-1 break-all font-mono text-xs">{workspace.id}</dd></div></dl><h3 className="mt-6 text-sm font-semibold">Available workspaces</h3><ul className="mt-2 divide-y">{session.workspaces.map((item) => <li key={item.id} className="flex items-center justify-between gap-3 py-3 text-sm"><span>{item.name}</span><span className="capitalize text-muted-foreground">{item.role}</span></li>)}</ul></section>}</StreamResource>
      </div>
    </div>
  </main>;
}
export const dynamic = "force-dynamic";
