import Link from "next/link";
import { ArrowLeft, CheckCircle2, CircleDot } from "lucide-react";

import { approveBundleAction, cancelBundleAction, cancelMissionAction, editBundleAction, prepareApprovalAction, rejectBundleAction, retryMissionAction } from "@/app/actions/missions";
import { MissionPoller } from "@/components/mission-poller";
import { MissionStatusBadge, formatRelativeTime } from "@/components/mission-status";
import { MutationForm } from "@/components/mutation-form";
import { Button } from "@/components/ui/button";
import { StreamResource } from "@/components/stream-resource";
import { Skeleton } from "@/components/ui/skeleton";
import { getApproval, getAssessment, getContextPack, getExecutions, getMission, getSla, getTimeline, requireSession } from "@/lib/api/server";
import { canManage, terminalMissionStatuses } from "@/lib/api/types";

export default async function MissionPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ approvalId?: string }> }) {
  const [{ id }, { approvalId }, session] = await Promise.all([params, searchParams, requireSession()]);
  const mission = await getMission(id);
  const manager = canManage(session.current_workspace.role);
  const lifecycle = ["Submitted", "Context", "Assessment", "Approval", "Execution", "Verification"];
  const lifecycleIndex: Record<string, number> = { queued: 0, planning: 0, context_collected: 1, waiting_for_approval: 3, running: 4, completed: 5, partially_complete: 5, blocked: 4, failed: 4, rejected: 3, cancelled: 0 };
  const currentStage = lifecycleIndex[mission.status] ?? 0;

  return <main className="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8">
    <Button nativeButton={false} variant="ghost" size="sm" render={<Link href="/missions" />} className="mb-4 -ml-2"><ArrowLeft className="size-4" />Missions</Button>
    <section className="mb-5 overflow-x-auto rounded-xl border bg-card px-5 py-4" aria-label="Mission lifecycle">
      <div className="grid min-w-[680px] grid-cols-6">{lifecycle.map((label, index) => <div key={label} className="relative flex items-center"><div className={`relative z-10 flex size-7 items-center justify-center rounded-full border font-mono text-[11px] ${index <= currentStage ? "border-primary bg-primary text-primary-foreground" : "bg-card text-muted-foreground"}`}>{index < currentStage ? <CheckCircle2 className="size-3.5" /> : index + 1}</div>{index < lifecycle.length - 1 && <div className={`absolute left-7 right-0 h-px ${index < currentStage ? "bg-primary" : "bg-border"}`} />}<span className={`ml-2 text-xs ${index <= currentStage ? "font-medium text-foreground" : "text-muted-foreground"}`}>{label}</span></div>)}</div>
    </section>
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1.55fr)_minmax(320px,.8fr)]">
      <div className="space-y-5">
        <section className="rounded-xl border bg-card p-5"><div className="flex flex-wrap items-center gap-2"><MissionStatusBadge status={mission.status} /><span className="font-mono text-xs text-muted-foreground">{mission.id}</span><span className="text-xs text-muted-foreground">Updated {formatRelativeTime(mission.updated_at)}</span></div><h1 className="mt-4 text-xl font-semibold leading-8 sm:text-2xl">{mission.prompt}</h1><div className="mt-5 flex flex-wrap gap-3 border-t pt-4 text-sm"><span className="rounded-md bg-muted px-2.5 py-1">{mission.project}</span><span className="text-muted-foreground">{mission.progress_current}/{mission.progress_total} steps</span><StreamResource promise={getSla(id)} label="SLA" fallback={<Skeleton className="h-5 w-28" />}>{(sla) => <span className={sla.breached ? "text-destructive" : "text-muted-foreground"}>SLA {sla.breached ? "breached" : `${Math.max(0, Math.round(sla.remaining_seconds / 60))}m remaining`}</span>}</StreamResource></div></section>

        <StreamResource promise={getTimeline(id)} label="Timeline">{(timeline) => <section className="rounded-xl border bg-card"><div className="border-b px-5 py-4"><h2 className="text-sm font-semibold">Durable timeline</h2></div><ol className="divide-y px-5">{timeline?.map((event) => <li key={event.id} className="grid grid-cols-[auto_1fr] gap-3 py-4"><CircleDot className="mt-1 size-4 text-primary" /><div><div className="flex flex-wrap justify-between gap-2"><h3 className="text-sm font-medium">{event.title}</h3><time className="font-mono text-xs text-muted-foreground">{formatRelativeTime(event.created_at)}</time></div><p className="mt-1 text-sm text-muted-foreground">{event.detail}</p>{event.correlation_id && <code className="mt-2 block text-xs text-muted-foreground">Correlation: {event.correlation_id}</code>}</div></li>)}{timeline?.length === 0 && <li className="py-8 text-center text-sm text-muted-foreground">No timeline events are available.</li>}</ol></section>}</StreamResource>

        <section className="rounded-xl border bg-card p-5"><h2 className="text-sm font-semibold">Mission steps</h2><div className="mt-3 space-y-3">{mission.steps.map((step) => <div key={step.id} className="flex gap-3 rounded-lg border p-3"><CheckCircle2 className="mt-0.5 size-4 text-success" /><div><p className="text-sm font-medium">{step.sequence}. {step.name}</p><p className="mt-1 text-xs text-muted-foreground">{step.status} · {step.detail}</p></div></div>)}{mission.steps.length === 0 && <p className="text-sm text-muted-foreground">No steps have been recorded.</p>}</div></section>
      </div>
      <aside className="space-y-5">
        <section className="rounded-xl border bg-card p-5"><h2 className="text-sm font-semibold">Result and controls</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">{mission.result_summary ?? "No result summary yet."}</p><div className="mt-4 space-y-3">{manager && !terminalMissionStatuses.has(mission.status) && <MutationForm action={cancelMissionAction.bind(null, id)} label="Cancel mission" variant="outline" />}{manager && ["blocked", "failed", "partially_complete"].includes(mission.status) && <MutationForm action={retryMissionAction.bind(null, id)} label="Retry mission" />}{manager && ["context_collected", "waiting_for_approval"].includes(mission.status) && <MutationForm action={prepareApprovalAction.bind(null, id)} label={mission.status === "waiting_for_approval" ? "Open latest approval" : "Prepare approval"} />}{!manager && <p className="text-xs text-muted-foreground">Your workspace role has read-only access to mission controls.</p>}</div></section>
        <StreamResource promise={getContextPack(id)} label="Context pack">{(context) => <section className="rounded-xl border bg-card p-5"><h2 className="text-sm font-semibold">Context pack · v{context.version}</h2><p className="mt-2 text-sm text-muted-foreground">{context.summary}</p><div className="mt-3 space-y-2">{context.evidence.map((item) => <div key={item.key} className="rounded-lg border p-3"><div className="text-sm font-medium">{item.title}</div><p className="mt-1 text-xs text-muted-foreground">{item.provider} · {item.excerpt}</p>{item.url && <a className="mt-2 block break-all text-xs text-primary hover:underline" href={item.url} target="_blank" rel="noreferrer">Open evidence</a>}</div>)}</div></section>}</StreamResource>
        <StreamResource promise={getAssessment(id)} label="Assessment">{(assessment) => <section className="rounded-xl border bg-card p-5"><h2 className="text-sm font-semibold">Agent assessment</h2><dl className="mt-3 grid grid-cols-2 gap-3 text-sm"><div><dt className="text-muted-foreground">Risk</dt><dd className="capitalize">{assessment.risk_level}</dd></div><div><dt className="text-muted-foreground">Confidence</dt><dd>{Math.round(assessment.confidence * 100)}%</dd></div><div><dt className="text-muted-foreground">Review effort</dt><dd>{assessment.review_effort_minutes}m</dd></div><div><dt className="text-muted-foreground">Mode</dt><dd className="capitalize">{assessment.mode}</dd></div></dl><p className="mt-3 text-sm text-muted-foreground">{assessment.explanation}</p>{assessment.risk_factors.length > 0 && <ul className="mt-3 list-disc space-y-1 pl-5 text-xs text-muted-foreground">{assessment.risk_factors.map((factor) => <li key={factor}>{factor}</li>)}</ul>}{assessment.reviewer_candidates.length > 0 && <div className="mt-4"><h3 className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">Reviewer candidates</h3>{assessment.reviewer_candidates.map((candidate) => <div key={candidate.identity} className="mt-2 rounded-lg border p-3 text-xs"><div className="font-medium">{candidate.identity} · {Math.round(candidate.score * 100)}%</div><p className="mt-1 text-muted-foreground">{candidate.reason}</p></div>)}</div>}</section>}</StreamResource>
        {approvalId && <StreamResource promise={getApproval(approvalId)} label="Approval">{(approval) => <section className="rounded-xl border bg-card p-5"><h2 className="text-sm font-semibold">Approval · v{approval.version}</h2><p className="mt-1 text-xs capitalize text-muted-foreground">{approval.status.replaceAll("_", " ")}</p>{approval.policy.reasons.length > 0 && <ul className="mt-3 list-disc space-y-1 pl-5 text-xs text-muted-foreground">{approval.policy.reasons.map((reason) => <li key={reason}>{reason}</li>)}</ul>}<div className="mt-3 space-y-2">{approval.actions.map((item) => <div key={item.id} className="rounded-lg border p-3"><div className="text-sm font-medium">{item.provider}: {item.operation}</div><p className="mt-1 text-xs text-muted-foreground">{item.rationale}</p></div>)}</div>{manager && <div className="mt-4 space-y-3"><MutationForm action={approveBundleAction.bind(null, id, approval.id)} label="Approve exact version"><input name="note" placeholder="Optional decision note" className="mb-2 min-h-10 w-full rounded-lg border bg-background px-3 text-sm" /></MutationForm><MutationForm action={rejectBundleAction.bind(null, id, approval.id)} label="Reject" variant="outline"><input name="note" placeholder="Optional rejection note" className="mb-2 min-h-10 w-full rounded-lg border bg-background px-3 text-sm" /></MutationForm><MutationForm action={cancelBundleAction.bind(null, id, approval.id)} label="Cancel approval" variant="outline" /><details className="rounded-lg border p-3"><summary className="cursor-pointer text-sm font-medium">Edit proposed actions</summary><MutationForm action={editBundleAction.bind(null, id, approval.id)} label="Save new version" variant="outline" className="mt-3"><textarea name="actions" defaultValue={JSON.stringify(approval.actions.map(({ provider, operation, rationale, payload, citations }) => ({ provider, operation, rationale, payload, citations })), null, 2)} className="mb-2 min-h-48 w-full rounded-lg border bg-background p-3 font-mono text-xs" /><input name="note" placeholder="Edit note" className="mb-2 min-h-10 w-full rounded-lg border bg-background px-3 text-sm" /></MutationForm></details></div>}</section>}</StreamResource>}
        <StreamResource promise={getExecutions(id)} label="Executions">{(executions) => <section className="rounded-xl border bg-card p-5">
          <h2 className="text-sm font-semibold">Executions</h2>
          <div className="mt-3 space-y-2">
            {executions.map((execution) => <div key={execution.id} className="rounded-lg border p-3">
              <div className="flex justify-between gap-2 text-sm"><span>{execution.provider} · {execution.operation}</span><span className="capitalize">{execution.status.replaceAll("_", " ")}</span></div>
              <p className="mt-1 text-xs text-muted-foreground">Attempts: {execution.attempts}{execution.external_id ? ` · External ID: ${execution.external_id}` : ""}</p>
              {execution.verification && <p className="mt-1 text-xs text-muted-foreground">Verification: {execution.verification.status}</p>}
              {execution.last_error && <p className="mt-1 text-xs text-destructive">{execution.last_error}</p>}
            </div>)}
            {executions.length === 0 && <p className="text-sm text-muted-foreground">No executions have been recorded.</p>}
          </div>
        </section>}</StreamResource>
      </aside>
    </div>
    <MissionPoller missionId={id} status={mission.status} approvalId={approvalId} />
  </main>;
}
